name = "gleebook"
version = "0.1.1"
description = "A modern, ultra-fast static site generator written in Gleam for building documentation."
licences = ["Apache-2.0"]

repository = { type = "github", user = "v4rm4n", repo = "gleebook" }
links = [{ title = "Gleebook", href = "https://v4rm4n.github.io/gleebook" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
glint = ">= 1.3.0 and < 2.0.0"
argv = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.7.0 and < 3.0.0"
gleam_community_ansi = ">= 1.5.0 and < 2.0.0"
lustre = ">= 5.7.1 and < 6.0.0"
contour = ">= 1.2.1 and < 2.0.0"
wisp = ">= 2.2.2 and < 3.0.0"
mist = ">= 6.0.3 and < 7.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
mork = ">= 1.12.1 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
