// src/gleebook/template.gleam
//
// The starter book written by `gleam run -m gleebook init`.
// Kept separate from the CLI so the template can be tested on its own.

import gleam/bool
import gleam/list
import gleam/result
import gleam/string
import simplifile

pub type InitError {
  /// A SUMMARY.md is already there; we never overwrite an existing book.
  AlreadyExists(path: String)
  WriteFailed(path: String, reason: simplifile.FileError)
}

/// Every file in the template, as `#(path relative to the book root, contents)`.
pub fn files() -> List(#(String, String)) {
  [
    #("SUMMARY.md", summary),
    #("index.md", index),
    #("writing.md", writing),
    #("guide/theming.md", theming),
    #("guide/deploying.md", deploying),
  ]
}

/// Write the starter book into `root` (normally "book").
/// Returns the paths that were written, in order.
pub fn scaffold(root: String) -> Result(List(String), InitError) {
  let summary_path = root <> "/SUMMARY.md"

  use exists <- result.try(
    simplifile.is_file(summary_path)
    |> result.map_error(WriteFailed(summary_path, _)),
  )
  use <- bool.guard(when: exists, return: Error(AlreadyExists(summary_path)))

  list.try_map(files(), fn(file) {
    let #(relative, contents) = file
    write_file(root <> "/" <> relative, contents)
  })
}

fn write_file(path: String, contents: String) -> Result(String, InitError) {
  use _ <- result.try(
    simplifile.create_directory_all(parent_dir(path))
    |> result.map_error(WriteFailed(path, _)),
  )
  use _ <- result.try(
    simplifile.write(to: path, contents: contents)
    |> result.map_error(WriteFailed(path, _)),
  )
  Ok(path)
}

fn parent_dir(path: String) -> String {
  case path |> string.split("/") |> list.reverse {
    [_, ..rest] if rest != [] -> rest |> list.reverse |> string.join("/")
    _ -> "."
  }
}

// -- Template contents --

const summary = "# My Book

- [Welcome](index.md)
- [Writing Pages](writing.md)
- [Guide]()
  - [Theming](guide/theming.md)
  - [Deploying](guide/deploying.md)
"

const index = "# Welcome to your book

This site was generated by **Gleebook**. Everything you see comes from the
Markdown files in the `book/` directory. Edit them, save, and the page in your
browser reloads on its own while `gleam run -m gleebook serve` is running.

> **Tip:** Blockquotes render as callouts like this one. Use them for tips,
> warnings and asides.

## Where to go from here

- **Add a page** — create a `.md` file in `book/` and list it in `SUMMARY.md`.
- **Learn the syntax** — [Writing Pages](writing.md) shows everything Gleebook can render.
- **Make it yours** — the [Theming](guide/theming.md) chapter shows how to change colours.
- **Ship it** — [Deploying](guide/deploying.md) covers building the static site.

```gleam
import gleam/io

pub fn main() {
  io.println(\"Hello from Gleebook!\")
}
```
"

const writing = "# Writing Pages

Gleebook renders CommonMark with the GitHub extensions, so anything you would
write in a README works here.

## Text formatting

You can write **bold**, *italic*, ~~strikethrough~~ and `inline code`. Links to
other chapters use the `.md` filename, like [the welcome page](index.md), and
are rewritten to `.html` at build time. Footnotes work too.[^1]

## Lists

1. Ordered lists
2. keep their numbers
   - and nest bullets
   - as deep as you like

- [x] Task lists work as well
- [ ] Check this one off

## Tables

| Feature   | Supported | Notes                            |
| :-------- | :-------: | -------------------------------: |
| Tables    |    Yes    | Alignment via the delimiter row  |
| Footnotes |    Yes    | Collected at the end of the page |
| Raw HTML  |    No     | Stripped for safety              |

## Callouts

> Blockquotes render as accented callout boxes. Inline **formatting** and
> `code` work inside them.

## Code blocks

Gleam code is highlighted natively; other languages use highlight.js. Every
block gets a copy button.

```gleam
pub fn greet(name: String) -> String {
  \"Hello, \" <> name <> \"!\"
}
```

```sh
gleam run -m gleebook build
```

## Images and video

Use standard image syntax. If the URL is a YouTube link, Gleebook embeds the
video player instead of an image:

```markdown
![A diagram](assets/diagram.png)
![Talk title](https://www.youtube.com/watch?v=VIDEO_ID)
```

[^1]: Footnotes are written as `[^1]` in the text and `[^1]: ...` anywhere in
    the file. They are collected at the bottom of the page.
"

const theming = "# Theming

Gleebook ships with two themes: **Cyberpunk Pink** (dark) and **Rust Olive**
(light). The toggle at the bottom of the sidebar switches between them, and the
choice is remembered in the browser.

You can also force a theme through the URL, which is handy for sharing links:

```
index.html?theme=cyberpunk
index.html?theme=olive
```

## Custom colours

`book/custom.css` is copied into the build and loaded after the built-in
styles, so anything in it wins. The themes are driven by CSS variables;
override the ones you want, per theme:

```css
[data-theme='cyberpunk'] {
  --gb-accent: #7dd3fc;
}

[data-theme='olive'] {
  --gb-accent: #b45309;
}
```

| Variable | Controls |
| --- | --- |
| `--gb-bg`, `--gb-text` | Page background and body text |
| `--gb-sidebar`, `--gb-border` | Sidebar background and borders |
| `--gb-accent` | Brand colour, links, active chapter |
| `--gb-nav-text`, `--gb-nav-hover`, `--gb-nav-active` | Sidebar link states |
| `--gb-code-bg`, `--gb-code-bar`, `--gb-code-bar-text` | Code block body and title bar |
| `--gb-callout` | Callout background |
| `--gb-syn-*` | Syntax highlighting palette |

Plain CSS works as well: the content column has the `gleebook-prose` class, so
`.gleebook-prose h2 { ... }` is a safe hook.
"

const deploying = "# Deploying

When the book is ready, compile it to static HTML:

```sh
gleam run -m gleebook build
```

The result lands in `build/gleebook/` and is completely self-contained: the
HTML pages, your `assets/` folder and `custom.css`. Upload that directory to any
static host — GitHub Pages, Netlify, Cloudflare Pages, an S3 bucket or a plain
web server. Links are relative, so it works from a sub-path too.

## Checklist

- [ ] Every chapter in `SUMMARY.md` has a matching `.md` file (the build warns about missing ones)
- [ ] `build/` is in your `.gitignore` (it is, if the project came from `gleam new`)
- [ ] Images referenced from pages live in `assets/`
"
